---
- name: Ensure backup directory exists
  file:
    path: "/root/.aap_etc_backup_{{ ansible_date_time.iso8601_basic }}"
    state: directory
    mode: 0644

- name: Backup /etc directory
  copy:
    src: /etc
    dest: "/root/.aap_etc_backup_{{ ansible_date_time.iso8601_basic }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy password-auth-ac to /etc/pam.d/password-auth-ac 
  copy:
    src: password-auth-ac
    dest: /etc/pam.d/password-auth-ac
    owner: root
    group: root
    mode: 0644

- name: Restore SELinux context for password-auth-ac
  command: restorecon -Rv /etc/pam.d/password-auth-ac

- name: Copy system-auth-ac to /etc/pam.d/system-auth-ac
  copy:
    src: system-auth-ac
    dest: /etc/pam.d/system-auth-ac
    owner: root
    group: root
    mode: 0644

- name: Restore SELinux context for system-auth-ac
  command: restorecon -Rv /etc/pam.d/system-auth-ac

- name: Copy passwd to /etc/pam.d/passwd
  copy:
    src: passwd
    dest: /etc/pam.d/passwd
    owner: root
    group: root
    mode: 0644

- name: Restore SELinux context for passwd
  command: restorecon -Rv /etc/pam.d/passwd

- name: Copy postlogin to /etc/authselect/postlogin
  copy:
    src: postlogin
    dest: /etc/authselect/postlogin
    owner: root
    group: root
    mode: 0644

- name: Restore SELinux context for postlogin
  command: restorecon -Rv /etc/authselect/postlogin
